server:
  port: 8080
  host: localhost
database:
  host: localhost
  port: 3306
  user: admin
  password: admin
  database: test
security:
  secret: secret
  jwt:
    key: 123456
    expiration: 3600
