server:
  port: 8080
  host: https://hdq.dev.vn
database:
  host: hdq.dev.vn
  port: 3306
  user: admin
  password: admin
  database: production
security:
  secret: secret
  jwt:
    key: 123456
    expiration: 3600